# Header
menu:
  首页: /
  归档: /archives

rss: /atom.xml
nav: right
mobile_nav: right



# Content
excerpt_link: 阅读全文
fancybox: true

# Sidebar
sidebar: right
widgets:
- userinfo
- category
- tag
- tagcloud
- archive
- recent_posts
- blogroll

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Background
# background_image: /images/bg.jpeg
background_title: 图片来自网络

# favicon
favicon: /images/default-avatar.jpg

#Userinfo
author: HeYzZ
slogan: 吾日三省吾身，早上吃什么，中午吃什么，晚上吃什么
# avatar: /images/code-title.png
avatar_title: 图片来自网络

# Article code panel: cloud doorframe mac
highlightPanel: cloud

#Gitment
gitment:
  owner: HeYzZe
  repo: blog-repo
  client_id: 4d8bd4bef7e5bdb2676d
  client_secret: 57dc4100da1686ed0f58018f33734a9e6b852bc3
  lazy: false

# Miscellaneous
google_analytics:
gauges_analytics:
google_site_verification: 
baidu_site_verification: 

# 友情链接
blogroll:
  一路眼瞎: https://yiluyanxia.github.io/